[package]
name = "cade"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.194", features = ["derive"] }
config = "0.13.4"
blake3 = "1.5.0"
lz4 = "1.24.0"
zstd = "0.13.0"
pathdiff = "0.2.1"

# needed for profiling
[profile.release]
debug = true

